### ISSUE TITLE
Sprint 3 documents

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#102]
### Descriptions
Write up the deliverables document for Sprint 3

### To-do
* [ ] Put the current user / system documentation into a deliverables doc
* [ ] Acceptance tests and user stories completed, with evidence
* [ ] If there were any additional features? Note down
