### ISSUE TITLE
Set up Traefik and Gunicorn

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#13]
### Description
Set up Nginx and Gunicorn to work with Flask.

### To-do

- [x] Set up Traefik
- [x] Set up Gunicorn
- [x] Write up documentation on how to work with Nginx and Gunicorn into the Readme

**Comment by sellsol** [comment]
Documentation in Readme not needed, it's just some config changes for Docker
