### ISSUE TITLE
Component documentation in client source code

### ISSUE THREAD

**Issue by keyman015** [nlp-tlp/15926-4-RDL-CITS3200#16]
### Description
Components should be appropriately documented so that developers can see, upon hovering, the required props for the component and example usage. It should look something like:
![image](https://github.com/user-attachments/assets/57d69f5f-f764-46a0-923a-f978c1df7b46)
![image](https://github.com/user-attachments/assets/95f20e77-e1e3-414e-b58d-9eedcf5efdb0)

### To-do
* [x] Update typescript configuration to allow the intellisense to pick up these documentation points.
* [x] Implement JSDoc style comments to components so its easy to understand everything about the component.
* [x] Update appriopriate scripts to show these documentation properly (must convert them to `export default ....`).
