### ISSUE TITLE
Set up web interface pages

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#2]
### Description
Set up some blank / default pages that we can start putting components onto. You may make basic design / naming decisions at your own discretion (will be checked later). 

### To-do
- [x] Landing page on route '/' and visualisation page on route '/graph'
- [x] Just a basic nice header for both pages with the site name (iso15926vis, or something nicer if you can think of it). Can be the same for both pages for now
- [x] Functional buttons on the headers for: home (landing), visualisation, and documentation
