### ISSUE TITLE
AWS Lightsail setup and CI/CD pipeline

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#22]
### Description
Now that we have access to the AWS account, set up a LightSail instance and configure the pipeline such that when a change goes into the main branch, they automatically show up on AWS. Might need to test using a separate test repo.

Currently thinking of using https://github.com/appleboy/ssh-action and https://github.com/appleboy/scp-action - LightSail has ssh by default that we can use the scp the changes 

### To-do
* [x] Create and setup personal LightSail instance
* [x] Write and test auto-deployment pipeline
* [x] Make proper setup and deploy on client LightSail instance
