### ISSUE TITLE
Info sidepane UI

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#23]
### Description
On the graph information sidepane (right), make it render mock RDF data for a class. Just copy any sufficiently detailed class and pass it into the sidepane from the main graph view, then make sure that it renders nicely. Essentially the rendering should be complete, and when we get the real data we only need to pass it in when needed. Maybe see how the [browser](https://data.15926.org/rdl) does it, and just make it fit in with the current simple UI. 

Any format for the data is fine for now - shouldn't be too difficult to change that when we put it all together. No need to make any metadata links work to complete this ticket. 

### To-do
* [x] Sidepane to render all metadata fields 

Make sure that:
* [x] Metadata longer than the height of the sidepane can be accessed through scroll
* [x] Metadata longer than the width of the sidepane wraps around
* [x] The difference between the field names and values are clear
