### ISSUE TITLE
Search sidepane UI

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#25]
### Description
Make some (non-functional) components for the graph search sidepane (left). Make a searchbar, and  dropdown left of or above the sidepane (whichever seems nicer to work with) that allows us to choose between id / uri, and the rdf label. The way we will query for searches is not yet decided so having a dropdown of results is out of scope for this ticket. 

Underneath the searchbar, make UI for the toggle for deprecation, the toggle for viewing labels in graph, and the inputs for number of hierarchy levels above / below node. 

### To-do
* [x] Dropdown for id / uri vs rdf label
* [x] Basic non-functional searchbar
* [x] Toggle for deprecation and view labels in graph
* [x] Input with up-and-down arrows for both number of hierarchy levels above and below. Maximum 6 for both.
