### ISSUE TITLE
Graph export

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#28]
### Needs
* #26 

### Description
In the main graph view, add a button (location TBD) with an icon for export. Clicking on the button should automatically produce a crop of the currently viewed graph data and show a preview to the user in a modal. The user should be able to choose between multiple common types of image formats, and when confirmed the image will be downloaded by the browser.

If the difficulty of getting different types of image formats working varies, let the team know so we can work out what is the most important and if there is need for other tickets focusing on adding particular ones in. Also the case with auto-cropping - may need a separate ticket to get it working. 

### To-do
* [x] Add an export icon button on the main graph view
* [x] Modal for export that comes up when icon button is clicked
* [x] Auto-convert current graph view to image, and preview in the export modal
* [x] Dropdown to select format
* [x] Confirm button downloads the image in selected format
