### ISSUE TITLE
Read-many API endpoint (full RDL)

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#29]
### Description
Make an API endpoint on the server that serves data for multiple nodes in a hierarchy. For now, just serve the full RDL - filtering to be implemented later. Only data needed for graphing should be sent - probably just the URIs and labels, as well as what is needed to interpret the hierarchical structure. 

### To-do
* [ ] Get all the RDL data from our database
* [ ] Serve data through read-many endpoint
* [ ] Error handling for bad requests
