### ISSUE TITLE
Initial landing page UI

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#3]
### Description
Draft and write up the planned contents of the landing page, including the purpose of our project, some brief explanations of ISO and the RDL, and our names and the collaboration between UWA and the ISO committee. Forgo the site instructions for now. You can make design choices at your discretion, check with others if unsure. 

See the sprint 1 proposal document for our purpose and RDL / ISO definitions. We have been given this as an example landing page by the client: [Living lab project](https://livinglabproject.com/) - although our project isn't as complicated, it should still look similarly polished. 

### To-do
* [x] Purpose of project
* [x] Definitions of ISO and RDL
* [x] Names and collaboration

**Comment by sellsol** [comment]
PR merged
