### ISSUE TITLE
Read-hierarchy-by-id API endpoint

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#32]
### Needs
* #4 

### Description
Create a read-hierarchy-by-id API endpoint, to serve the local hierarchy of a node. Return all of 6 levels above and 6 levels below such that the selected node is a direct descendant / ancestor. Only data needed for graphing should be sent - URIs, labels, deprecation date, as well as what is needed to interpret the hierarchical structure. No need to deal with multiple parents for now, do as you wish (let the team know).

The intention is to hide / show the correct levels on the frontend. Hopefully local hierarchies won't be as heavy as the full graph, but let the team know if there are still concerns about size. 

Most likely this will use similar functionality to 
* #55 

can think of reusing some functions maybe?

### To-do
* [x] Get 6 levels above and below a node from our database
* [x] Convert to nested json in the format the frontend wants
* [x] Create endpoint and serve local hierarchy data

**Comment by sellsol** [comment]
Changed scope of ticket to dedicated read-by-id api, since we're no longer doing a read-many api for the full graph.

**Comment by keyman015** [comment]
Apologies, I seem to have moved the wrong issue. Restating original status to continue work.
