### ISSUE TITLE
Dynamic loading on node expansion

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#36]
### Needs
* #55 
* #26 

### Description
Collapsibility is already implemented. On each expansion, make it so that now the frontend queries the backend's read-children-by-id endpoint and inserts it into the graph. On collapse, we are probably going to delete the data (or relocate / cache it somewhere else maybe?) - let the team know about complexity and concerns about fetching data multiple times quickly

This may be useful to you: https://github.com/fhightower/d3-dynamic-tree 

### To-do
- [x] Get data from backend
- [x] Insert new data into the graph's data on expand
- [x] Remove data from graph's data on collapse
