### ISSUE TITLE
Fill documentation pages

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#41]
### Description
Ensure that all documentation pages are detailed and filled in such that anyone can easily follow the steps to perform the tasks that they need - admin, maintainer, developer. 

### To-do
* [x] Admin documentation page
* [x] Maintainer documentation page
* [x] Developer documentation page
* [x] Changelog page - this one can just be the initial log
