### ISSUE TITLE
Set up backend testing framework

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#5]
### Description
Set up a testing directory for backend unit tests, and add a testing process into the Github workflow so that code that doesn't pass these tests cannot be merged into main. Write one or two very basic ones just to be sure they work (at your discretion).  

### To-do
- [x] Set up backend testing framework
- [x] Write one or two basic unit tests
- [x] Integrate into Github workflow
