### ISSUE TITLE
Public web interface snapshots

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#54]
### Description
Showcase current capabilities and list some future planned features in a public place / as a flyer, so that it can be used to show other people and get them excited. Make this look nice (or at least decent enough that people won't be put off).

The team thinks that it could be good to make a tab for this on our already public documentation site and put the info there. Let the team and client know if this is good or if you have a better / easier idea. This is a more urgent task as requested by client.

### To-do
* [x] Put up some screenshots of the web interface in action, that we have currently. Graph most important
* [x] Make a list of some important planned items and also put it up on the flyer
* [x] Let team and client know for further feedback

**Comment by paulmmaingi** [comment]
Currently awaiting feedback from the client.

**Comment by paulmmaingi** [comment]
Client approved the document.

[ISO_visualisation_progress_update.pdf](https://github.com/user-attachments/files/17008206/ISO_visualisation_progress_update.pdf)

**Comment by paulmmaingi** [comment]
[progress_update_v2.pdf](https://github.com/user-attachments/files/17045530/progress_update_v2.pdf)

Updated as per client requests.
