### ISSUE TITLE
Read-children-by-id API endpoint

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#55]
### Description
For our dynamic loading strategy, the frontend will fetch new nodes from the backend when a node is expanded. Create an endpoint to serve the children of a given node.

Might need some discussion - I was thinking that if the called node is "Thing", you would also just serve "Thing" itself (it's our root node). A separate endpoint seemed like overkill but let Heidi know if it overcomplicates things.

### To-do
* [ ] New endpoint with id query parameter
* [ ] Get a single node's direct children from the database
* [ ] Serve the direct children with their id, labels and deprecation date if applicable
* [ ] Deal with sending back "Thing"
