### ISSUE TITLE
Sprint 2 documents

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#56]
### Description
Write the documents due for the end of sprint 2. This includes the user stories done sprint 2 (against planned for sprint 2) and user stories planned for sprint 3. Plan the agenda items for both the team and client retrospective meetings. Let the team know for proof-checking.

### To-do
* [x] User stories done for sprint 2, vs planned
* [x] User stories planned for sprint 3
* [x] Proofreading by team
* [x] Submit documents

**Comment by vinita254** [comment]
As required, agendas for the meetings tomorrow (16/09/2024) have been shared with the current Project Manager, Paul. The agendas are as follows:

Group Meeting (Internal Project Retrospective) Agenda:
- Reports and Progress
- Flyer Review
- User Stories Discussion + Assess Current Progress
- Challenges and Next Steps (set goals for sprint 3)
- User Stories Adjustment + Managing Client's Expectations?
- Questions for Client

Client Meeting (Client Project Retrospective) Agenda:
- Informal Project Demonstration
- Client Feedback
- Questions for Client
- User Stories Adjustments?

**Comment by vinita254** [comment]
Updated the agenda items, as per Heidi's request:

Group Meeting (Internal Project Retrospective) Agenda:
- Reports and Progress
- User Stories Discussion + Assess Current Progress
- Challenges and Next Steps (set goals for sprint 3)
- Questions for Client

Client Meeting Agenda:
- Informal Project Demonstration
- Client Retrospective
- Questions for Client + Feedback

**Comment by paulmmaingi** [comment]
The Sprint 2 documents have been submitted and sent to the client. They included both the team and client retrospectives, the sprint 2 user stories progress, the planned user stories for sprint 3 and the updated flyer document sent to the client. They were proofread and edited by the Team. Attached below in case needed.

[CITS3200_ISO15926_4__Team_14.pdf](https://github.com/user-attachments/files/17045323/CITS3200_ISO15926_4__Team_14.pdf)
