### ISSUE TITLE
Research and prepare for AWS account setup (IAM)

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#6]
### Description
We are planning on using AWS LightSail for deployment, and are meeting with the client on Monday the 26th to set things up. Research and try going through the deployment process before that meeting. 

### To-do
* [x] Account setup with MFA and budgeting
* [x] Research about specific services and separate pricings in AWS LightSail 
* [x] Get limited permission roles / accounts set up on personal account
* [x] Write up pricing notes and sequence of steps to-do ready for meeting with client

### Removed
* Get the current code to deploy on AWS LightSail - Too much to do before the Monday meeting. IAM was complicated enough... Will get this done at a later date
