### ISSUE TITLE
Set up frontend testing framework

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#7]
### Description
Set up a testing directory for frontend unit tests, and add a testing process into the Github workflow so that code that doesn't pass these tests cannot be merged into main. Write one or two very basic ones just to be sure they work (at your discretion).  

### To-do
- [x] Set up frontend testing framework
- [x] Write one or two basic unit tests
- [x] Integrate into Github workflow
- [x] Update Readme for documentation

**Comment by sellsol** [comment]
PR merged in
