### ISSUE TITLE
Cleaning up the repository

### ISSUE THREAD

**Issue by paulmmaingi** [nlp-tlp/15926-4-RDL-CITS3200#73]
### Needs
Everything else Completed

### Description
Final action items for Project

### To-do
* [x] Prune empty/unused branches on Github repository
* [x] Delete the massive Github deployment history
* [x] Clean up readme and take out the 'in construction' stuff
* [x] Get Git commit logs to submit as a deliverable
* [x] Make tag for final version of code

**Comment by sellsol** [comment]
Can we remove the setup script when this happens pls and run through the readme commands - it only works for linux and is just something else to maintain

**Comment by sellsol** [comment]
Removed 'Update Flask API CORS to only accept requests from the deployed site to prevent unwanted requests' - we already have traefik routing
