### ISSUE TITLE
Styling pass

### ISSUE THREAD

**Issue by paulmmaingi** [nlp-tlp/15926-4-RDL-CITS3200#74]
### Needs
Functional components of project completed

### Description
The site should be aesthetically pleasing with an intuitive colour scheme and clean, well spaced design. For inspiration, the client would like the styling for the main page to follow the [Living lab](https://livinglabproject.com/) styling and for the documentation to follow the  [IndEEA](https://indeaa-docs.systemhealthlab.com/developer/) documentation.

### To-do

* [ ] Label display and positioning so as not to block other items. 
* [ ] Change app name and icon
* [ ] Consistent styling for landing / graph pages
** To be added when this is picked up.
