### ISSUE TITLE
Initial documentation pages

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#9]
### Description
Write up a skeleton for our mkdoc documentation pages and make it available in the browser. Let's go with pages for: Developer, maintainer, administrator, and changelog. Just a description for each is fine for now. 

The client had given us this as an example: [Indeaa documentation](https://indeaa-docs.systemhealthlab.com/)

### To-do
* [x] Documentation pages for developer, maintainer, administrator, changelog
* [ ] Descriptions for each of the above pages
* [x] Route the 'Documentation' button in our frontend to the docs
