### ISSUE TITLE
Final minor cosmetic changes

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#99]
### To-do
* [ ] Larger width between levels of the hierarchy
* [x] White halos on graph label text
* [x] Change some parts of the left sidepane to the deeper colour in the right sidepane (search, dropdown, submit at your discretion so it looks good and feels more like the other one)
* [x] iso15926vis title to not be that greyish colour. See maybe the non-white white tone in the right sidepane
